import interpret_CAN
print("Testing")
print(interpret_CAN.interpret(0,"AB"))
print(interpret_CAN.interpret(10, "ABCD"))
print(interpret_CAN.interpret(11, "ABCDEFG"))
print(interpret_CAN.interpret(12, "ABCDEF"))
print(interpret_CAN.interpret(13, "ABCDEF"))
print(interpret_CAN.interpret(0xE0, "ABCDEFGH"))
print(interpret_CAN.interpret(0xE1, "ABCDªªªª"))
print(interpret_CAN.interpret(0xE1, "ABCDUUUU"))
print(interpret_CAN.interpret(0xE2, "ABCDEFGH"))
print(interpret_CAN.interpret(0xE3, "ABCDEFGH"))
print(interpret_CAN.interpret(0xE4, "ABCDEFGH"))
print(interpret_CAN.interpret(0xE5, "ABCDEFGH"))
print(interpret_CAN.interpret(0xE6, "ABCDEFGH"))
print(interpret_CAN.interpret(0xE7, "ABCDEFGH"))
print(interpret_CAN.interpret(0xE8, "ABCDEFGH"))
print(interpret_CAN.interpret(0xE9, "ABCDEFGH"))
print(interpret_CAN.interpret(0xEA, "ABCDEFGH"))
print(interpret_CAN.interpret(0xEB, "ABCDEFGH"))
print(interpret_CAN.interpret(0xEC, "ABCDEFGH"))
print(interpret_CAN.interpret(0xED, "ABCDEFGH"))
print(interpret_CAN.interpret(0xEE, "ABCDEFGH"))
print(interpret_CAN.interpret(0xF7, "ABCDEFGH"))

