import interpret_CAN
print("Testing")
print(interpret_CAN.interpret(0,bytes("AB")))
print(interpret_CAN.interpret(1,bytes("AB")))
print(interpret_CAN.interpret(10,bytes("ABCD")))
print(interpret_CAN.interpret(11,bytes( "ABCDEFG")))
print(interpret_CAN.interpret(12,bytes( "ABCDEF")))
print(interpret_CAN.interpret(13,bytes( "ABCDEF")))
print(interpret_CAN.interpret(0xE0,bytes( "ABCDEFGH")))
print(len("ABCDªªªª"))
print(interpret_CAN.interpret(0xE1,bytes( "ABCDªªªª")))
print(interpret_CAN.interpret(0xE1,bytes( "ABCDUUUU")))
print(interpret_CAN.interpret(0xE2,bytes( "ABCDEFGH")))
print(interpret_CAN.interpret(0xE3,bytes( "ABCDEFGH")))
print(interpret_CAN.interpret(0xE4,bytes( "ABCDEFGH")))
print(interpret_CAN.interpret(0xE5,bytes( "ABCDEFGH")))
print(interpret_CAN.interpret(0xE6,bytes( "ABCDEFGH")))
print(interpret_CAN.interpret(0xE7,bytes( "ABCDEFGH")))
print(interpret_CAN.interpret(0xE8,bytes( "ABCDEFGH")))
print(interpret_CAN.interpret(0xE9,bytes( "ABCDEFGH")))
print(interpret_CAN.interpret(0xEA,bytes( "ABCDEFGH")))
print(interpret_CAN.interpret(0xEB,bytes( "ABCDEFGH")))
print(interpret_CAN.interpret(0xEC,bytes( "ABCDEFGH")))
print(interpret_CAN.interpret(0xED,bytes( "ABCDEFGH")))
print(interpret_CAN.interpret(0xEE,bytes( "ABCD\0FGH")))
print(interpret_CAN.interpret(0xF7,bytes( "ABCDEFGH")))

